# ingressRoute:
#   dashboard:
#     enabled: true
#     entryPoints:
#       - web
# service:
#   type: ClusterIP

service:
  type: LoadBalancer
  annotations:
    metallb.universe.tf/address-pool: default
