apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Traefik CRDs
  # - https://raw.githubusercontent.com/traefik/traefik-helm-chart/v37.2.0/crds/crds.yaml
  # Gateway CRDs
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.0/standard-install.yaml
  - dashboard_route.yaml

helmCharts:
  - name: traefik
    version: 37.2.0
    repo: "https://traefik.github.io/charts"
    releaseName: traefik
    namespace: traefik
    valuesFile: values.yaml
