providers:
  kubernetesIngress:
    publishedService:
      enabled: false     #if you want to use with kubernetes ingress, set it to true.
  kubernetesGateway:
    enabled: true

gateway:
  namespacePolicy: All


# Add this section to enable the API
additionalArguments:
  - "--api.dashboard=true"
  - "--api.insecure=true"

# Add ports section to expose the API
ports:
  traefik:
    port: 9000
    expose:
      enabled: true
    exposedPort: 9000

ingressRoute:
  dashboard:
    enabled: true
    entryPoints:
    - web
    - websecure

service:
  enabled: true
  spec:
    externalTrafficPolicy: Local
  annotations:
    service.beta.kubernetes.io/metal-lb: "true"
    metallb.universe.tf/address-pool: public-pool
  type: LoadBalancer
  ports:
    web:
      port: 80
      targetPort: 80
    websecure:
      port: 443
      targetPort: 443
  
dashboard:
  enabled: true
  ingress:
    enabled: true
    path: /dashboard/
    pathType: Prefix
    annotations:
      kubernetes.io/ingress.class: traefik
    hosts:
    - host: "*" #traefik.example.com  # Change to your desired host
      paths:
      - /
