apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

resources:
  - pvc.yaml
  - pg-secret.yaml
  - pg-cluster.yaml

helmCharts:
  - name: immich
    version: 0.10.1
    repo: "https://immich-app.github.io/immich-charts"
    releaseName: immich
    namespace: immich
    valuesFile: values.yaml
