apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
  - name: sealed-secrets
    version: 2.34.0
    repo: "https://bitnami-labs.github.io/sealed-secrets"
    releaseName: sealed-secrets
    valuesFile: values.yaml
