apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          # # Helm-based applications
          # - name: pihole
          #   namespace: pihole
          #   type: helm
          #   chart: pihole
          #   repoURL: https://mojo2600.github.io/pihole-kubernetes/
          #   version: 2.34.0
          
          # # Kustomize-based applications
          # - name: immich
          #   namespace: immich
          #   url: "https://google.com"
          #   type: kustomize
            
  template:
    metadata:
      name: '{{.name}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: applications
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
  templatePatch: |
    metadata:
      annotations:
        {{- if .url }}
        link.argocd.argoproj.io/external-link: "{{.url}}"
        {{- end }}
    {{- if eq .type "helm"}}
    spec:
      sources:
        - repoURL: '{{.repoURL}}'
          chart: '{{.chart}}'
          targetRevision: '{{.version}}'
          helm:
            releaseName: '{{.name}}'
            valueFiles:
              - $values/applications/{{.name}}/values.yaml
        - repoURL: https://github.com/tomas-rojo/tomas-homelab-test-1.git
          targetRevision: HEAD
          ref: values
    {{- else}}
    spec:
      source:
        repoURL: https://github.com/tomas-rojo/tomas-homelab-test-1.git
        targetRevision: HEAD
        path: applications/{{.name}}
    {{- end}}
