apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ip_address_pool.yaml
  - l2_advertisment.yaml

helmCharts:
  - name: metallb
    version: 0.15.3
    repo: "https://metallb.github.io/metallb"
    releaseName: metallb
    namespace: metallb-system
    valuesFile: values.yaml
