apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cnpg
    version: "0.26.0"
    repo: "https://cloudnative-pg.github.io/charts"
    releaseName: cnpg
    valuesFile: values.yaml
