apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cnpg-system

helmCharts:
  - name: cloudnative-pg
    version: 0.26.0
    repo: "https://cloudnative-pg.github.io/charts"
    releaseName: cloudnative-pg
    valuesFile: values.yaml
